### ISSUE TITLE
Issue with unpublishing from NPME and beta tags

### ISSUE THREAD

**Issue by mudrummer012** [npm/npme-installer#153]
To reproduce:

- Module currently sits at some version (1.0.9)
- Publish a new version with a beta tag (new version 1.1.0-0)
- Bump the version and publish without a beta tag (new version 1.1.0)
- Realize you cant use the 1.1.0 version yet so you unpublish 1.1.0.
- Latest tag will now be 1.1.0-0 (the beta tag that should never be latest).
- Realize the issue and try to run npm dist-tag and set 1.0.9 back to latest.
- Get the following error:

```bash
user@computer:~/projects/path/to/module$ npm dist-tag add @scope/module@2.2.0 latest
npm WARN tag This command is deprecated. Use `npm dist-tag` instead.

npm ERR! registry error parsing json
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/XXXXXXXX/.nvm/versions/node/v4.4.4/bin/node" "/Users/XXXXXXXX/.nvm/versions/node/v4.4.4/bin/npm" "tag" "@XXXXXXXXXX/YYYYYYYYYYYY@2.2.0" "latest"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1

npm ERR! Unexpected token S
npm ERR! SyntaxError: Unexpected token &quot;<br> &nbsp; &nbsp;at parse (/etc/npme/node_modules/@npm/couch-url-rewrite-proxy/node_modules/body-parser/lib/types/json.js:83:1
5)<br> &nbsp; &nbsp;at /etc/npme/node_modules/@npm/couch-url-rewrite-proxy/node_modules/body-parser/lib/read.js:116:18<br> &nbsp; &nbsp;at invokeCallback (/etc/npme/node_mo
dules/@npm/couch-url-rewrite-proxy/node_modules/body-parser/node_modules/raw-body/index.js:262:16)<br> &nbsp; &nbsp;at done (/etc/npme/node_modules/@npm/couch-url-rewrite-p
roxy/node_modules/body-parser/node_modules/raw-body/index.js:251:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/etc/npme/node_modules/@npm/couch-url-rewrite-proxy/node_modu
les/body-parser/node_modules/raw-body/index.js:307:7)<br> &nbsp; &nbsp;at emitNone (events.js:67:13)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:166:7)<br> &nbsp; &
nbsp;at endReadableNT (_stream_readable.js:905:12)<br> &nbsp; &nbsp;at nextTickCallbackWith2Args (node.js:437:9)<br> &nbsp; &nbsp;at process._tickCallback (node.js:351:17)
```

Tried the npm dist-tag rm modulename latest then readd and got the same error.

**Comment by bcoe** [comment]
@mudrummer012 digging into this now.

**Comment by bcoe** [comment]
@mudrummer012 just published a new release of npm Enterprise which fixes the `npm dist-tag add` behavior 👍 

Let me know if it does the trick for you, and feel free to reopen this issue.
