### ISSUE TITLE
broken on install: notarget request, missing policy-follower, can't publish

### ISSUE THREAD

**Issue by garthk** [npm/npme-installer#49]
Sorry if this is tangled, but I'm not sure where the causes stop and effects start. 

TL,DR: installing under the Docker container doesn't seem to work:

```
npm ERR! Linux 3.13.0-30-generic
npm ERR! argv "node" "/etc/npme/node_modules/.bin/npm" "install" "--registry=https://enterprise.npmjs.com" "--always-auth"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.7
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: request@'>=2.49.0 <3.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.10.0","0.8.3","0.9.0","0.9.1","0.9.5","1.0.0","1.1.0","1.1.1","1.2.0","1.9.0","1.9.1","1.9.2","1.9.3","1.9.5","1.9.7","1.9.8","1.9.9","2.0.0","2.0.1","2.0.2","2.0.3","2.0.4","2.0.5","2.1.0","2.1.1","2.2.0","2.2.5","2.2.6","2.2.9","2.9.0","2.9.1","2.9.2","2.9.3","2.9.100","2.9.150","2.9.151","2.9.152","2.9.153","2.9.200","2.9.201","2.9.202","2.9.203","2.10.0","2.11.0","2.11.1","2.11.2","2.11.3","2.11.4","2.12.0","2.14.0","2.16.0","2.16.2","2.16.4","2.16.6","2.18.0","2.19.0","2.20.0","2.21.0","2.22.0","2.23.0","2.24.0","2.25.0","2.26.0","2.27.0","2.28.0","2.29.0","2.30.0","2.31.0","2.32.0","2.33.0","2.34.0","2.35.0","2.36.0","2.37.0","2.38.0","2.39.0","2.40.0","2.41.0","2.42.0","2.43.0","2.44.0","2.45.0","2.46.0","2.47.0","2.48.0"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /etc/npme/npm-debug.log
restarting services
Not running
Not running
Not running
Not running
Starting registry-frontdoor
Starting policy-follower
  /etc/init.d/policy-follower: 38: cd: can't cd to /etc/npme/node_modules/@npm/policy-follower
  restart /etc/init.d/registry-frontdoor
```

… then, after install success, repeated problems in `policy-follower.log`:

```
==> ./logs/policy-follower.log <==

module.js:340
    throw err;
          ^
Error: Cannot find module '/bin/policy-follower.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

After logging in:

```
==> ./logs/registry-frontdoor.log <==
unknown user format passed to recordUser(): undefined
```

Trying to publish:

```
==> ./logs/npm-auth-ws.log <==
authorize with credentials { method: 'PUT',
  path: '/@COMPANY%2fMODULE',
  headers: 
   { 'accept-encoding': 'gzip',
     authorization: 'Bearer …',
     version: '2.2.0',
     accept: 'application/json',
     referer: 'publish',
     'npm-session': 'a8f7247f0bf89621',
     'user-agent': 'npm/2.2.0 node/v0.10.35 darwin x64',
     host: '…',
     'content-type': 'application/json',
     'content-length': '1225',
     connection: 'keep-alive' },
  body: 
   { _id: '@ COMPANY/MODULE',
     name: '@ COMPANY/MODULE',
     description: '',
     'dist-tags': { latest: '1.0.0' },
     versions: { '1.0.0': [Object] },
     readme: 'ERROR: No README data found!',
     _attachments: { '@ COMPANY/MODULE-1.0.0.tgz': [Object] } } }
attempting to authorize publish

==> ./logs/registry-frontdoor.log <==
authFetch enabled; verifying all requests

==> ./logs/npm-auth-ws.log <==
authorization error [TypeError: Cannot read property 'url' of undefined]

==> ./logs/registry-frontdoor.log <==
authFetch is false; GETs and HEADs are not checked
package read handler; package=/registry/@COMPANY%2fMODULE?sharedFetchSecret=change-me-to-a-secure-token
readHandler couch error: status=404; body={"error":"not_found","reason":"missing"}

auth service returned 500 -> {"success":false,"error":"Cannot read property 'url' of undefined"}
```

… and the client reports:

```
npm ERR! publish Failed PUT 401
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.10.35
npm ERR! npm  v2.2.0
npm ERR! code E401

npm ERR! Request was not authorized : @COMPANY%2fMODULE
```

**Comment by bcoe** [comment]
@garthk it looks like a few days ago a version of the policy-follower was released that relied on version `2.49.0` of request, which was not in the npmE installer registry.

I've fixed this issue, mind trying to install again. I've also fixed the root cause of the problem, so hopefully this won't come up again.

**Comment by garthk** [comment]
That seems to have done the trick, @bcoe. Thanks.

**Comment by mandalae** [comment]
Hi,

I'm posting in here because it seems related. I'm getting that same error in my logs with an installation I did just yesterday.

Here's what I see when I try to start or restart npme on the docker image:
```
root@cdd369a7242d:/etc/npme# npme start
starting services:
Starting npm-auth-ws
  /etc/init.d/npm-auth-ws: 38: cd: can't cd to /etc/npme/node_modules/@npm/npm-auth-ws
Starting registry-frontdoor
  /etc/init.d/registry-frontdoor: 38: cd: can't cd to /etc/npme/node_modules/@npm/registry-frontdoor
Starting validate-and-store
  /etc/init.d/validate-and-store: 38: cd: can't cd to /etc/npme/node_modules/@npm/validate-and-store
Starting policy-follower
  /etc/init.d/policy-follower: 38: cd: can't cd to /etc/npme/node_modules/@npm/policy-follower
  start /etc/init.d/npm-auth-ws
  start /etc/init.d/registry-frontdoor
  start /etc/init.d/policy-follower
  start /etc/init.d/validate-and-store
npmE is now running (curl http://localhost:8080).
root@cdd369a7242d:/etc/npme# curl http://localhost:8080
curl: (7) Failed to connect to localhost port 8080: Connection refused
root@cdd369a7242d:/etc/npme# npme restart
restarting services
Not running
Not running
Not running
Not running
Starting npm-auth-ws
  /etc/init.d/npm-auth-ws: 38: cd: can't cd to /etc/npme/node_modules/@npm/npm-auth-ws
Starting policy-follower
  /etc/init.d/policy-follower: 38: cd: can't cd to /etc/npme/node_modules/@npm/policy-follower
  restart /etc/init.d/npm-auth-ws
  restart /etc/init.d/policy-follower
Starting registry-frontdoor
  /etc/init.d/registry-frontdoor: 38: cd: can't cd to /etc/npme/node_modules/@npm/registry-frontdoor
Starting validate-and-store
  /etc/init.d/validate-and-store: 38: cd: can't cd to /etc/npme/node_modules/@npm/validate-and-store
  restart /etc/init.d/validate-and-store
  restart /etc/init.d/registry-frontdoor
```

Hopefully I'm just doing something wrong, but I can't really see what it is? The @npm directory seems to be completely missing.
