### ISSUE TITLE
“npm install” stalls when requiring modules from npme

### ISSUE THREAD

**Issue by avector** [npm/npme-installer#53]
I have a docker ubuntu image running for veryfying and testing the workflow with npme. npm install'ing from the public index works fine, but when I try to install from the private npme index (which I'm currently running on an Amazon EC2 instance), the install process stalls while attempting to load the tarball from 127.0.0.1:8080.

The logs on the EC2 instance show that the original login:

```npm login --registry=http://ec2-www-xxx-yyy-zzz.us-west-2.compute.amazonaws.com:8080 --scope=@mycompany```

comes through fine and auth is accepted. When running npm install @mycompany/my-private-package, the request comes through fine on the EC2 instance, the registry-frontdoor.log shows

```
authorized OK
package read handler; package=/registry/@mycompany%2fmy-private-package
forwarding 200 response from couchdb
```

But the client hangs, and the npm-debug.log shows:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'install', '@mycompany/my-private-package', '--save-dev' ]
2 info using npm@2.7.3
3 info using node@v0.10.37
4 verbose node symlink /usr/bin/node
5 warn package.json test@1.0.0 No description
6 warn package.json test@1.0.0 No repository field.
7 warn package.json test@1.0.0 No README data
8 silly cache add args [ '@mycompany/my-private-package', null ]
9 verbose cache add spec @mycompany/my-private-package
10 silly cache add parsed spec { raw: '@mycompany/my-private-package',
10 silly cache add   scope: '@mycompany',
10 silly cache add   name: '@mycompany/my-private-package',
10 silly cache add   rawSpec: '',
10 silly cache add   spec: '*',
10 silly cache add   type: 'range' }
11 verbose addNamed @mycompany/my-private-package@*
12 silly addNamed semver.valid null
13 silly addNamed semver.validRange *
14 silly addNameRange { name: '@mycompany/my-private-package', range: '*', hasData: false }
15 silly mapToRegistry name @mycompany/my-private-package
16 silly mapToRegistry scope (from package name) @mycompany
17 silly mapToRegistry registry http://ec2-www-xxx-yyy-zzz.us-west-2.compute.amazonaws.com:8080/
18 silly mapToRegistry uri http://ec2-www-xxx-yyy-zzz.us-west-2.compute.amazonaws.com:8080/@mycompany%2fmy-private-package
19 verbose addNameRange registry:http://ec2-www-xxx-yyy-zzz.us-west-2.compute.amazonaws.com:8080/@mycompany%2fmy-private-package not in flight; fetching
20 verbose request uri http://ec2-www-xxx-yyy-zzz.us-west-2.compute.amazonaws.com:8080/@mycompany%2fmy-private-package
21 verbose request no auth needed
22 info attempt registry request try #1 at 14:25:53
23 verbose request using bearer token for auth
24 verbose request id 8c4499c1234e0363
25 verbose etag "12-f9676c44a20d6c11d0ebb66c14f43851"
26 http request GET http://ec2-www-xxx-yyy-zzz.us-west-2.compute.amazonaws.com:8080/@mycompany%2fmy-private-package
27 http 200 http://ec2-www-xxx-yyy-zzz.us-west-2.compute.amazonaws.com:8080/@mycompany%2fmy-private-package
28 silly get cb [ 200,
28 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
28 silly get     etag: '"12-f9676c44a20d6c11d0ebb66c14f43851"',
28 silly get     date: 'Thu, 26 Mar 2015 14:25:54 GMT',
28 silly get     'content-type': 'application/json',
28 silly get     'content-length': '17980',
28 silly get     'cache-control': 'must-revalidate',
28 silly get     connection: 'keep-alive' } ]
29 verbose get saving @mycompany/my-private-package to /root/.npm/ec2-www-xxx-yyy-zzz.us-west-2.compute.amazonaws.com_8080/_40eb_252fmy-private-package/.cache.json
30 silly addNameRange number 2 { name: '@mycompany/my-private-package', range: '*', hasData: true }
31 silly addNameRange versions [ '@mycompany/my-private-package',
31 silly addNameRange   [ '0.1.0',
31 silly addNameRange     '0.1.1',
31 silly addNameRange     '0.1.2',
31 silly addNameRange     '0.1.3',
31 silly addNameRange     '0.2.0',
31 silly addNameRange     '0.2.2',
31 silly addNameRange     '0.2.3',
31 silly addNameRange     '0.2.4',
31 silly addNameRange     '0.3.0',
31 silly addNameRange     '0.3.1',
31 silly addNameRange     '0.3.2',
31 silly addNameRange     '0.4.0' ] ]
32 verbose addNamed @mycompany/my-private-package@0.4.0
33 silly addNamed semver.valid 0.4.0
34 silly addNamed semver.validRange 0.4.0
35 silly mapToRegistry name @mycompany/my-private-package
36 silly mapToRegistry scope (from package name) @mycompany
37 silly mapToRegistry registry http://ec2-www-xxx-yyy-zzz.us-west-2.compute.amazonaws.com:8080/
38 silly mapToRegistry uri http://ec2-www-xxx-yyy-zzz.us-west-2.compute.amazonaws.com:8080/@mycompany%2fmy-private-package
39 verbose addRemoteTarball http://127.0.0.1:8080/@/@mycompany/my-private-package/_attachments/my-private-package-0.4.0.tgz not in flight; adding
40 verbose addRemoteTarball [ 'http://127.0.0.1:8080/@/@mycompany/my-private-package/_attachments/my-private-package-0.4.0.tgz',
40 verbose addRemoteTarball   'ac1c07735ad8e7099595eb377135d113d816a6a9' ]
41 info retry fetch attempt 1 at 14:25:54
42 info attempt registry request try #1 at 14:25:54
43 http fetch GET http://127.0.0.1:8080/@/@mycompany/my-private-package/_attachments/my-private-package-0.4.0.tgz
44 verbose request using bearer token for auth
45 info retry will retry, error on last attempt: Error: connect ECONNREFUSED
46 info attempt registry request try #2 at 14:26:04
47 http fetch GET http://127.0.0.1:8080/@/@mycompany/my-private-package/_attachments/my-private-package-0.4.0.tgz
48 verbose request using bearer token for auth
49 info retry will retry, error on last attempt: Error: connect ECONNREFUSED
50 info attempt registry request try #3 at 14:27:04
51 http fetch GET http://127.0.0.1:8080/@/@mycompany/my-private-package/_attachments/my-private-package-0.4.0.tgz
52 verbose request using bearer token for auth
53 error fetch failed http://127.0.0.1:8080/@/@mycompany/my-private-package/_attachments/my-private-package-0.4.0.tgz
54 warn retry will retry, error on last attempt: Error: connect ECONNREFUSED
55 info retry fetch attempt 2 at 14:27:14
56 info attempt registry request try #1 at 14:27:14
57 http fetch GET http://127.0.0.1:8080/@/@mycompany/my-private-package/_attachments/my-private-package-0.4.0.tgz
58 verbose request using bearer token for auth
59 info retry will retry, error on last attempt: Error: connect ECONNREFUSED
60 info attempt registry request try #2 at 14:27:24
61 http fetch GET http://127.0.0.1:8080/@/@mycompany/my-private-package/_attachments/my-private-package-0.4.0.tgz
62 verbose request using bearer token for auth
63 info retry will retry, error on last attempt: Error: connect ECONNREFUSED
64 info attempt registry request try #3 at 14:28:24
65 http fetch GET http://127.0.0.1:8080/@/@mycompany/my-private-package/_attachments/my-private-package-0.4.0.tgz
66 verbose request using bearer token for auth
67 error fetch failed http://127.0.0.1:8080/@/@mycompany/my-private-package/_attachments/my-private-package-0.4.0.tgz
68 warn retry will retry, error on last attempt: Error: connect ECONNREFUSED
69 info retry fetch attempt 3 at 14:29:24
70 info attempt registry request try #1 at 14:29:24
71 http fetch GET http://127.0.0.1:8080/@/@mycompany/my-private-package/_attachments/my-private-package-0.4.0.tgz
72 verbose request using bearer token for auth
73 info retry will retry, error on last attempt: Error: connect ECONNREFUSED
74 info attempt registry request try #2 at 14:29:34
75 http fetch GET http://127.0.0.1:8080/@/@mycompany/my-private-package/_attachments/my-private-package-0.4.0.tgz
76 verbose request using bearer token for auth
77 info retry will retry, error on last attempt: Error: connect ECONNREFUSED
78 info attempt registry request try #3 at 14:30:34
79 http fetch GET http://127.0.0.1:8080/@/@mycompany/my-private-package/_attachments/my-private-package-0.4.0.tgz
80 verbose request using bearer token for auth
81 error fetch failed http://127.0.0.1:8080/@/@mycompany/my-private-package/_attachments/my-private-package-0.4.0.tgz
82 verbose stack Error: connect ECONNREFUSED
82 verbose stack     at errnoException (net.js:905:11)
82 verbose stack     at Object.afterConnect [as oncomplete] (net.js:896:19)
83 verbose cwd /root/test
84 error Linux 3.18.5-tinycore64
85 error argv "node" "/usr/bin/npm" "install" "@mycompany/my-private-package" "--save-dev"
86 error node v0.10.37
87 error npm  v2.7.3
88 error code ECONNREFUSED
89 error errno ECONNREFUSED
90 error syscall connect
91 error Error: connect ECONNREFUSED
91 error     at errnoException (net.js:905:11)
91 error     at Object.afterConnect [as oncomplete] (net.js:896:19)
91 error  { [Error: connect ECONNREFUSED]
91 error   code: 'ECONNREFUSED',
91 error   errno: 'ECONNREFUSED',
91 error   syscall: 'connect',
91 error   parent: 'test' }
92 error If you are behind a proxy, please make sure that the
92 error 'proxy' config is set properly.  See: 'npm help config'
93 verbose exit [ 1, true ]
```

Knowing little abot the internals of npme, the thing that stands out is the line ```verbose addRemoteTarball http://127.0.0.1:8080/@/@mycompany/my-private-package/_attachments/my-private-package-0.4.0.tgz not in flight``` – as I have nothing running on 127.0.0.1:8080.

**Comment by bcoe** [comment]
@avector there's now a new installer available that should make getting an instance of npm Enterprise up and running a bit easier:

https://gist.github.com/bcoe/5d3efe3e4a518789a7bb

Please feel free to reopen this ticket if this doesn't do the trick for you.
