### ISSUE TITLE
Installation broken on RHEL 7? Error: Cannot find module 'nan' while installing @npm/registry-frontdoor

### ISSUE THREAD

**Issue by marcellodesales** [npm/npme-installer#61]
Hi there,

I'm seeing a bug while installing this on RHEL7... Not sure... Install goes well for a good time till it says "configuration complete"...

```
TASK: [bcoe.npme | chown db directory] **************************************** 
ok: [127.0.0.1]

TASK: [bcoe.npme | more restrictive permissions] ****************************** 
changed: [127.0.0.1] => (item=package.json)
changed: [127.0.0.1] => (item=service.json)

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=11   changed=2    unreachable=0    failed=0   

configuration complete!
```

Then, the installation just gets broken after the next few lines... 

```
npm WARN package.json @npm/npm-enterprise-services@2.0.0 No README data
npm WARN package.json @npm/npm-enterprise-services@2.0.0 No license field.

> xxhash@0.2.2 install /etc/npme/node_modules/@npm/registry-frontdoor/node_modules/light-cycle/node_modules/xxhash
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/etc/npme/node_modules/@npm/registry-frontdoor/node_modules/light-cycle/node_modules/xxhash/.node-gyp"
\
module.js:340
    throw err;
          ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:559:25)
    at startup (node.js:80:7)
    at node.js:929:3
gyp: Call to 'node -e "require('nan')"' returned exit status 8. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/etc/npme/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.10.0-229.4.2.el7.x86_64
gyp ERR! command "node" "/etc/npme/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /etc/npme/node_modules/@npm/registry-frontdoor/node_modules/light-cycle/node_modules/xxhash
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
 
> ursa@0.8.5 install /etc/npme/node_modules/@npm/registry-frontdoor/node_modules/ursa
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/etc/npme/node_modules/@npm/registry-frontdoor/node_modules/ursa/.node-gyp"
\
module.js:340
    throw err;
          ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:559:25)
    at startup (node.js:80:7)
    at node.js:929:3
gyp: Call to 'node -e "require('nan')"' returned exit status 8. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/etc/npme/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.10.0-229.4.2.el7.x86_64
gyp ERR! command "node" "/etc/npme/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /etc/npme/node_modules/@npm/registry-frontdoor/node_modules/ursa
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 

> dtrace-provider@0.3.2 install /etc/npme/node_modules/@npm/npm-auth-ws/node_modules/restify/node_modules/dtrace-provider
> node scripts/install.js
```

The installation fails at the following

```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/etc/npme/node_modules/@npm/validate-and-store/node_modules/multi-fs/node_modules/manta-client/node_modules/manta/node_modules/bunyan/node_modules/dtrace-provider/.node-gyp"
make: Entering directory `/etc/npme/node_modules/@npm/validate-and-store/node_modules/multi-fs/node_modules/manta-client/node_modules/manta/node_modules/bunyan/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory `/etc/npme/node_modules/@npm/validate-and-store/node_modules/multi-fs/node_modules/manta-client/node_modules/manta/node_modules/bunyan/node_modules/dtrace-provider/build'
npm ERR! Linux 3.10.0-229.4.2.el7.x86_64
npm ERR! argv "node" "/etc/npme/node_modules/.bin/npm" "install" "--userconfig=/etc/npme/.npmrc" "--always-auth" "--registry=https://enterprise.npmjs.com"
npm ERR! node v0.10.36
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE

npm ERR! xxhash@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xxhash@0.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the xxhash package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls xxhash
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /etc/npme/npm-debug.log
......................................................................................................................................................................................................
```

I got the successful installation message just once... :( I was redoing the installation by removing the /etc/npme directory, but I still can't proceed... 

Any help here?

**Comment by marcellodesales** [comment]
Just got past this step

**Comment by bcoe** [comment]
@marcellodesales, I'm glad you got past this -- what was the hiccup in RHEL 7? Is it something we can patch on our end.

**Comment by marcellodesales** [comment]
@bcoe I think the latest changes solved most of it... The only blocking steps are documented at https://github.com/npm/npme-installer/issues/63#issuecomment-113963451... Here's the step-by-step process to install the registry on RHEL 7 with the hacks needed to be done... 

https://gist.github.com/marcellodesales/6a771a412a9e4aef6476

Right now, the only thing that's not working is the CouchDB vhost setup...
